spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordertesting
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
server:
  port: 8011
adminuserprivilege:
  name:
    role_management_view:"Role Management View"